# Render Readme.md with rmarkdown and then deploy render and deploy pkgdown website to gh-pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

name: Render Readme and pkgdown

jobs:
  render:
    name: Render Readme and pkgdown
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            local::.
            any::devtools
            any::kableExtra
            any::rmarkdown
            any::pkgdown

      - name: Render README.md using rmarkdown
        run: Rscript -e 'rmarkdown::render("README.Rmd", output_format = "github_document")'

      - name: Commit rendered README
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md README.html
          git commit -m "Re-build README.md" || echo "No changes to commit"
          git push origin master || echo "No changes to commit"

      - name: Deploy pkgdown package
        if: success()
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE, run_dont_run = FALSE)'
