# Render Readme.md with rmarkdown and then deploy render and deploy pkgdown website to gh-pages

on:
  push:
    branches:
      - main
      - master

name: Render Readme and pkgdown

jobs:
  render:
    name: Render Readme and pkgdown
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: 'true'
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install rmarkdown, remotes, and the local package
        run: |
          # For readme
          install.packages("remotes")
          remotes::install_local(".")
          remotes::install_cran("rmarkdown")
          remotes::install_cran("devtools")
          remotes::install_cran("kableExtra")
          # For pkgdown
          remotes::install_deps(dependencies = TRUE)
          install.packages("pkgdown", type = "binary")
        shell: Rscript {0}

      - name: Render README.md using rmarkdown
        run: Rscript -e 'rmarkdown::render("README.Rmd", output_format = "github_document")'

      - name: Commit rendered README
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md README.html
          git commit -m "Re-build README.md" || echo "No changes to commit"
          git push origin master || echo "No changes to commit"

      - name: Deploy pkgdown package
        if: success()
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE, run_dont_run = FALSE)'
